# Generated by Django 3.2.12 on 2022-02-22 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricsDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('avg_heartbeat', 'AVG_HEARTBEAT'), ('calories_consumed', 'CALORIES_CONSUMED'), ('sleep_hours', 'SLEEP_HOURS'), ('morning_pulse', 'MORNING_PULSE')], max_length=100)),
                ('data', models.ManyToManyField(to='metricdatapoint.SpesData')),
            ],
        ),
        migrations.CreateModel(
            name='Metricdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_data', to='metricdatapoint.metricsdatapoint')),
                ('y', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_data', to='metricdatapoint.metricsdatapoint')),
            ],
        ),
    ]
