# Generated by Django 4.0.2 on 2022-03-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data_type', models.CharField(choices=[('avg_heartbeat', 'AVG_HEARTBEAT'), ('calories_consumed', 'CALORIES_CONSUMED'), ('sleep_hours', 'SLEEP_HOURS'), ('morning_pulse', 'MORNING_PULSE')], max_length=100, null=True)),
                ('y_data_type', models.CharField(choices=[('avg_heartbeat', 'AVG_HEARTBEAT'), ('calories_consumed', 'CALORIES_CONSUMED'), ('sleep_hours', 'SLEEP_HOURS'), ('morning_pulse', 'MORNING_PULSE')], max_length=100, null=True)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_data', to='metricdatapoint.spesdata')),
                ('y', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_data', to='metricdatapoint.spesdata')),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metricdatapoint.metricdatapoint')),
            ],
        ),
    ]
