# Generated by Django 3.2.12 on 2022-02-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricsDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data_type', models.CharField(choices=[('AVG_HEARTBEAT', 'avg_heartbeat'), ('CALORIES_CONSUMED', 'calories_consumed'), ('SLEEP_HOURS', 'sleep_hours'), ('MORNING_PULSE', 'morning_pulse')], max_length=100)),
                ('y_data_type', models.CharField(choices=[('AVG_HEARTBEAT', 'avg_heartbeat'), ('CALORIES_CONSUMED', 'calories_consumed'), ('SLEEP_HOURS', 'sleep_hours'), ('MORNING_PULSE', 'morning_pulse')], max_length=100)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_data', to='metricdatapoint.spesdata')),
                ('y', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_data', to='metricdatapoint.spesdata')),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
