# Generated by Django 3.2.12 on 2022-02-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metricdatapoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdata',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metricdatapoint.metricsdatapoint'),
        ),
    ]
