# Generated by Django 3.2.12 on 2022-02-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metricdatapoint', '0002_metricdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricdata',
            name='data',
        ),
    ]
