# Generated by Django 3.2.12 on 2022-02-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metricdatapoint', '0003_remove_metricdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdata',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metricdatapoint.metricsdatapoint'),
        ),
        migrations.AlterField(
            model_name='spesdata',
            name='date',
            field=models.DateField(),
        ),
    ]
